### ISSUE TITLE
(Github) issues best practices as part of the development process?

### ISSUE THREAD

**Issue by bluepeter** [wearehive/project-guidelines#10]
Having a section on issues best practices, particularly as it relates to development, would be useful. E.g.:

- All non-trivial commits should tie back to a single issue
- Issues should have acceptance criteria (and... other stuff... possibly user stories/etc, but could get too much into "product" land)
- Issues should be closed via commit messages to better create a paper trail to document issue origination to code commit.
- Label usage

... something like that anyway? I personally favor Github Issues, but this section could be agnostic (or have separate issue tracker carveouts?)

**Comment by vpanjganj** [comment]
I personally think "Issues best practices" targets certain size of projects. If you look at the rest of the best(common) practices in this document, you see that apart from being very code oriented, you can apply them on small personal projects as well. 
But lets keep this issue open.

**Comment by vpanjganj** [comment]
I added [issue 32](https://github.com/wearehive/project-guidelines/issues/32). It doesn't discuss "issues best practices" directly, but you might be interested. If you don't mind I close this issue.
