### ISSUE TITLE
Why should console logs be avoided ?

### ISSUE THREAD

**Issue by MagixInTheAir** [wearehive/project-guidelines#116]
_Why : "Even though your build process can(should) get rid of them, make sure that your code style checker warns you about leftover console logs."_

As a beginner, this doesn't explain me (at all) why it should be avoided. Printing startup data (ip/port etc...) doesn't seem to hurt, does it ?

Thanks for clearing-up this point :)

**Comment by vpanjganj** [comment]
Hi @MagixInTheAir , 
Console logs are usually for you or your colleagues involved in development not for the client who uses the app in production. It’s also recommended in the eslint config we use (which is Airbnb). 

https://eslint.org/docs/rules/no-console

**Comment by MagixInTheAir** [comment]
I Understand. I think this should be pointed out in the guidelines :)
Thank you very much

**Comment by vpanjganj** [comment]
Yes I should. Also feel free to make a PR 😊

**Comment by luftywiranda13** [comment]
unless you're developing CLI app
