### ISSUE TITLE
Git workflow suggestion: add repo init steps

### ISSUE THREAD

**Issue by springdo** [wearehive/project-guidelines#19]
Hello Team Hive!

Great job on this so far, I would suggest in the git workflow section you add steps to setup a repository which are currently missing. I would like to add these as the first steps. They will give you standard branches used in your workflow (ie develop / feature / bugFix etc)

```
git init
git flow init
```

More than happy to PR

**Comment by vpanjganj** [comment]
I personally never used `git flow init`, I have to look into it a bit. The git steps mentioned are very frequent and happen a lot on a daily work, while git init is just once. I think it needs a small brief section at the beginning. If you make a pull request we can work on that.

**Comment by springdo** [comment]
Cool - I can do that so
👍
