### ISSUE TITLE
Add a section on Git hooks

### ISSUE THREAD

**Issue by yeskunall** [wearehive/project-guidelines#27]
This would be a good addition to the guide as they encourage a good commit policy and push you towards implementing continuous integration workflows.

There are a few good tools that make git hooks easy such as [husky](https://github.com/typicode/husky), among others.

If approved, I can start working on adding this to the guide. Let me know your thoughts.

Cheers! ❤️

**Comment by vpanjganj** [comment]
>altering the project environment depending on the state of the repository

I'm not sure if I understood this bit. Will you explain bit more please?
I suggest we promote `git hooks` in the [7. Code style](https://github.com/wearehive/project-guidelines#7-code-style-). We add a sub-section called **Code style check**, and then discuss about different stages code style checking can be applied(commit, build, deploy). Additionally we can also discuss [prettier](https://github.com/prettier/prettier).

What are your thought?

**Comment by yeskunall** [comment]
My bad, that one sentence I added does not apply here. Removed.

I agree. It should probably be added under chapter 7.

I am actually familiar with a workflow that includes using [lint-staged](https://github.com/okonet/lint-staged) with [husky](https://github.com/typicode/husky) with [prettier](https://github.com/prettier/prettier), so I can help add a section on it, if you'd like.

**Comment by vpanjganj** [comment]
@yeskunall I can get this done if you don't have time :)

**Comment by yeskunall** [comment]
I was just waiting for approval. Expect a PR soon! ❤️

**Comment by yeskunall** [comment]
@vpanjganj closing this now.
