### ISSUE TITLE
Remove Enunciate and Miredot from list of API design tools

### ISSUE THREAD

**Issue by yeskunall** [wearehive/project-guidelines#30]
Since this guide mainly focuses on JS projects, I think we should remove [Enunciate](http://enunciate.webcohesion.com/) and [Miredot](http://www.miredot.com/) from the list.

Thoughts?

**Comment by vpanjganj** [comment]
I agree. Do you have time for a quick PR?
Also `Swagger` needs to be a link.

**Comment by yeskunall** [comment]
Yes, sir. PR coming up!
