### ISSUE TITLE
reasons why

### ISSUE THREAD

**Issue by gautaz** [wearehive/project-guidelines#40]
Hello,

Nice initiative !

However, a set of rules is never well followed when one does not fully understand why the rules were enacted. It also helps to adhere to a rule when one knows what can occur if the rule is ignored.

I think that along with the list of rules, the reasons why each of them was written this way should also be detailed (through hyperlinks to not clutter the rules list itself). Pointing to issues that occurred when a rule was not followed would also help.

**Comment by vpanjganj** [comment]
Thanks for the feedback. I'm actually working on that at the moment. I'm not sure if should wait to finish all the sections. Or merge what I've done so far. I've finished the Git section. Each bullet point is followed by a `why:` paragraph that ends with a `read more...` link.

**Comment by vpanjganj** [comment]
@gautaz here is an example:

* Before making a Pull Request, make sure your feature branch builds successfully and passes all tests (including code style checks).
    
    **_why:_**
    > You are about to add your code to a stable branch. If your feature-branch tests fails, there is a high chance that your destination branch build will fail. Additionaly you need to apply code style check before making a Pull Request.It aids readability and reduces the chance of formatting fixes being mingled in with actual changes.

**Comment by vpanjganj** [comment]
Shall I close this ? @gautaz

**Comment by gautaz** [comment]
Hello,

Sorry for being so late to answer, I am always in a hurry (7 children at home :-)).

Unless you want to keep this issue as a reminder, you can close it.

**Comment by vpanjganj** [comment]
7 :D Jesus 

I've already added 'why' to more than half of them. I'll finish with all of them soon.

Thanks again for your comment. More than welcome to contribute
