### ISSUE TITLE
.env or .env* ?

### ISSUE THREAD

**Issue by ajoslin103** [wearehive/project-guidelines#45]
various frameworks support multiple .env files (using naming conventions) to support multiple target destinations

**Comment by vpanjganj** [comment]
Cool, do you suggest going into details, or just stick to a brief mention.

**Comment by ajoslin103** [comment]
how about this:

```
# dotenv environment variables file(s)
.env
.env.*
```

**Comment by vpanjganj** [comment]
Is it possible to make a pull request ? :)

**Comment by ajoslin103** [comment]
done (and thanks for this repo - I like it!)
