### ISSUE TITLE
Suggest clearer formatting for Dependencies section

### ISSUE THREAD

**Issue by bluepeter** [wearehive/project-guidelines#5]
This formatting is a bit confusing. It looks as though, e.g., you are suggesting that the user do `ls | npm Documentation` (i.e., UNIX `ls` command piped to `npm Documentation`). It also won't be clear to new users that one must prepend the `npm` command. I recommend changing this formatting to formatted code `npm ls` with a "documentation" link after and clearly differentiated from the code example.

![screenshot-github com-2017-07-05-18-25-25](https://user-images.githubusercontent.com/2158187/27860516-975cd118-61af-11e7-902d-b2be548156fb.png)

**Comment by vpanjganj** [comment]
You're absolutely right @bluepeter . Do you like to make a pull-request? I understand if you're busy in which case let me know and I'll do it myself.

**Comment by bluepeter** [comment]
Sure, I can do that.

**Comment by gyg3** [comment]
1
