### ISSUE TITLE
API Versioning library

### ISSUE THREAD

**Issue by lirantal** [wearehive/project-guidelines#51]
I like the part about API design, it's in a nutshell and concise.

If I may, the API Versioning part is actually dear to me since we've been rolling this solution out at work and I spun-up a modular and lightweight middleware for Express which does exactly that: https://github.com/lirantal/express-version-route 

Would it be ok to reference it in the README?

**Comment by vpanjganj** [comment]
Hi @lirantal , Sorry for my late reply. To be honest with you our approach is minimum use of libraries. Most of the dependencies we mentioned are dev tools. What I suggest is that you write a good content on why this form of API Versioning is a good practice (you can promote your lib there). Then I will link to that article in the `why:` section. What do you think?

**Comment by lirantal** [comment]
Sounds great, I'll shoot a PR soon enough!
