### ISSUE TITLE
Duplicate title

### ISSUE THREAD

**Issue by rdsedmundo** [wearehive/project-guidelines#58]
```
Write testable code, avoid side effects, extract side effects, write pure functions
```

Appears two times.

I guess it's a mistake? In the first section, there's only explanation about Pure Functions, so I think that its title could be 'Write Pure Functions'.

**Comment by vpanjganj** [comment]
Ah thanks a lot. I'll fix that tomorrow . If you have time, feel free to make a pull request (remove the first one and its  `why` paragraph).

**Comment by rdsedmundo** [comment]
Done.
