### ISSUE TITLE
Can I translate this guideline to Korean?

### ISSUE THREAD

**Issue by HyunSeob** [wearehive/project-guidelines#68]
I want to translate this guideline by forking a repo if you approve.

**Comment by vpanjganj** [comment]
Yes sure. If you don't mind keeping it updated

**Comment by HyunSeob** [comment]
Thanks!

**Comment by vpanjganj** [comment]
@HyunSeob our chinese version is up. Are you still interested ?

**Comment by HyunSeob** [comment]
Sure, I want Korean version, not Chinese.

**Comment by vpanjganj** [comment]
I know @HyunSeob, what I mean is you can always have a pull request back here with your Korean version and add a link to the main `README.md` file

**Comment by HyunSeob** [comment]
Ah, I get it. Thanks.

**Comment by vpanjganj** [comment]
@1984weed Amazing. Please make a pull request when you're done :)

**Comment by gaohailang** [comment]
where is the Chinese version? has it been done? if not, I will work to make progress on it~ @vpanjganj
