### ISSUE TITLE
Confusion about `git rebase` in the Gitflow part of doc

### ISSUE THREAD

**Issue by GeekaholicLin** [wearehive/project-guidelines#84]
Hey. Thanks for your awesome project guidlines.

In the en doc, there is one step in the Gitflow that maked me confused when I polished the zh one.

> Update your feature branch with latest changes from develop by interactive rebase.
    git checkout <branchname>
    git rebase -i --autosquash develop

To my certain knowledge which may be wrong, the `git rebase -i --autosquash develop` command is used to update **develop** branch with the changes you have make in the feature branch. Did I misunderstand it? Look forward to your reply.

**Comment by vpanjganj** [comment]
Hi, My understanding is that, `git rebase -i --autosquash develop` while you're in feature branch, will update your feature branch with new changes done on develop. Then it will add your feature commits on top of them. The result will be an updated feature branch which wont cause any conflicts.

**Comment by GeekaholicLin** [comment]
If it is as you've said, the develop branch will be removed from the common ancestor of the two branches and append it onto the feature branch, right? If so, you **shouldn't** remove feature branch in later step. 

Please see the Figure 37 and its explains above in [Pro Git](https://git-scm.com/book/en/v2/Git-Branching-Rebasing).

When woking on `experiment` branch using `git checkout experiment`, the next command `git rebase master` will cause "rebasing the change introduced in C4(experiment) onto C3(master)" as it says.

**Comment by GeekaholicLin** [comment]
Well, maybe I misunderstood what you mean.
There is an updated feature branch because of the inserted front master branch, while an updated develop branch because of the appended feature branch.They are all right, depending on where you are standing in. 
hum...But I still stick to my opion cause the next step you push will change the develop branch.It is to say that develop branch will be updated.

**Comment by vpanjganj** [comment]
So according to the link:
>It works by going to the common ancestor of the two branches (the one you’re on and the one you’re rebasing onto), getting the diff introduced by each commit of the branch you’re on, saving those diffs to temporary files, 

This is all the new feature stuff you've done so far. It puts it on a side. Now your feature branch looks like an old base branch.

>resetting the current branch to the same commit as the branch you are rebasing onto,

your feature branch (that looks like old base branch) now takes all the commits it has missed out. "rebasing re-writes the project history by creating brand new commits for each commit in the original branch."

>and finally applying each change in turn.
Now your feature commits gets applied on top. And you have a updated feature branch.

To be honest you gave me doubts too :D

**Comment by GeekaholicLin** [comment]
:joy: I am so sorry.
And thanks a lot! I think I know the whole work flow.
Update the feature branch and push it using `-f` to remote like github.And in the remote, make pull request so that the feature branch can be merged into develop branch.

And I made a mistake thinking the current working branch is develop but acturally the feature one.Therefore, we **must** use  `-f` to update the remote feature branch to force changes.

OK, And this issue can be closed.Thanks~
