### ISSUE TITLE
Add .editorconfig 

### ISSUE THREAD

**Issue by crobinson42** [wearehive/project-guidelines#90]
# http://editorconfig.org

Is extremely useful for projects with more than 1 developer working on the code!

**Comment by vpanjganj** [comment]
Does it have any feature that ESlint doesn't cover ?

**Comment by crobinson42** [comment]
@vpanjganj It's a bit different than ESlint. 

Have you ever pulled a repo that someone else was working on and say they prefer spaces over tabs and your editor is configured to use tabs, well, you'll have an annoying time there! 

This project utility is supported by all commonly used IDEs. When you open a project, your IDE will read the `.editorconfig` file and automatically use the configuration specified so all is in harmony.

Here's an example `.editorconfig`

```
# http://editorconfig.org
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```

**Comment by vpanjganj** [comment]
@crobinson42 Cool,
You happy to make a PR? :)
It can go under `7.2 Enforcing code style standards`.
