### ISSUE TITLE
This project itself doesn't follow these guidelines

### ISSUE THREAD

**Issue by ice1000** [wearehive/project-guidelines#97]
Like, there's no develop or any other branches (which is considered necessary in this guideline). Everyone pushes directly to the master branch.

I don't know if it's proper (for opening an issue like this). Sorry for bothering, I just want to provide my personal opinion.

**Comment by vpanjganj** [comment]
Hi @ice1000, I know what you mean. But most of the best practices discussed here are for developing a software. The nature of process involved in developing a feature within a team makes it necessary to use branching. But this repo is simply a document, not a software, new features are usually a paragraph. If I want to do a major change in the content or the way it's presented I may make a develop branch and start using feature branches.

**Comment by jeffhuys** [comment]
I'm curious @vpanjganj, and I hope you don't mind me asking you here.

We (as a company) have worked for the longest time with a `master`, `development` and `feature/` branches, we found that the `development` branch is not needed, provided that you have up-to-par tests and can QA on a `feature/` branch. In our case, why would we ever need a `development` branch?

**Comment by vpanjganj** [comment]
Hey, @jeffhuys. 
In some occasions in my company we needed to make the latest features available for a limited number of users before the actual release. Plus this had to be automated so they could see them as soon as it merges. There was a need to keep track of more than one live version of the same app, and having a develop branch really helped us.
